language: c
compiler: gcc
dist: trusty
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update --recursive

script:
    - export CC=gcc-5
    - mkdir build
    - cd build 
    - cmake ../
    - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - libcurl4-gnutls-dev

